// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.1";

// src/lib/mcp/tools/list-postes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-postes.ts
var list_postes_default = defineTool({
  name: "list_postes",
  title: "Lister les postes",
  description: "Liste les postes de recrutement accessibles \xE0 l'utilisateur connect\xE9.",
  inputSchema: {
    status: z.enum(["draft", "active", "archived"]).optional().describe("Filtrer par statut du poste."),
    limit: z.number().int().min(1).max(100).default(20).describe("Nombre maximum de postes retourn\xE9s.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id, title, job_title, status, language, slug, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { postes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-candidats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_candidats_default = defineTool2({
  name: "list_candidats",
  title: "Lister les candidats",
  description: "Liste les sessions candidats, avec filtre optionnel par poste, statut ou recherche sur le nom.",
  inputSchema: {
    poste_id: z2.string().uuid().optional().describe("Identifiant du poste \xE0 filtrer."),
    status: z2.enum(["pending", "in_progress", "completed", "cancelled", "expired"]).optional().describe("Statut de la session candidat."),
    search: z2.string().trim().min(1).optional().describe("Recherche sur le nom du candidat."),
    limit: z2.number().int().min(1).max(100).default(20).describe("Nombre maximum de candidats retourn\xE9s.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ poste_id, status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("sessions").select(
      "id, project_id, candidate_name, candidate_email, status, started_at, completed_at, duration_seconds, recruiter_decision"
    ).eq("is_demo", false).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (poste_id) query = query.eq("project_id", poste_id);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("candidate_name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { candidats: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-rapport.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_rapport_default = defineTool3({
  name: "get_rapport",
  title: "Rapport d'entretien",
  description: "R\xE9cup\xE8re le rapport d'\xE9valuation d'une session candidat : score, synth\xE8se, points forts et axes de progr\xE8s.",
  inputSchema: {
    session_id: z3.string().uuid().describe("Identifiant de la session candidat.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("reports").select(
      "id, session_id, overall_score, overall_grade, recommendation, executive_summary, executive_summary_short, strengths, areas_for_improvement, criteria_scores, generated_at"
    ).eq("session_id", session_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Aucun rapport disponible pour cette session." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rapport: data }
    };
  }
});

// src/lib/mcp/tools/get-transcript.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_transcript_default = defineTool4({
  name: "get_transcript",
  title: "Transcription d'entretien",
  description: "R\xE9cup\xE8re les \xE9changes transcrits d'une session candidat, dans l'ordre chronologique.",
  inputSchema: {
    session_id: z4.string().uuid().describe("Identifiant de la session candidat.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("session_messages").select("*").eq("session_id", session_id).order("created_at", { ascending: true }).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qxszgsxdktnwqabsdfvw";
var mcp_default = defineMcp({
  name: "interw",
  title: "Interw",
  version: "0.1.0",
  instructions: "Outils Interw pour le recrutement par entretien vid\xE9o asynchrone. Utilise list_postes pour retrouver un poste, list_candidats pour ses candidats, puis get_rapport et get_transcript pour analyser un entretien.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_postes_default, list_candidats_default, get_rapport_default, get_transcript_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
